[theme]
primaryColor="#2ecc71"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8f9fa"
textColor="#262730"
font="sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[email]
username = "harpinder.singh@rvsolutions.in"
password = "@BaljeetKaur529"  # Use an app-specific password for Gmail