[theme]
primaryColor="#2ecc71"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8f9fa"
textColor="#262730"
font="sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[smtp]
server = "mail.rvsolutions.in"
port = 587
username = "harpinder.singh@rvsolutions.in"
password = "@BaljeetKaur529"
from_email = "harpinder.singh@rvsolutions.in"